#=================================================
# https://github.com/zhangsean/docker-speedtest-web
# Description: Auto build speedtest-go and release zhangsean/speedtest-web using GitHub Actions
# License: Apache V2.0
# Author: ZhangSean
#=================================================

name: Auto build docker images

on:
  watch:
    types: [started]
    if: github.event.repository.owner.id == github.event.sender.id
  push:
    paths:
      - .github/workflows/build.yml
      - Dockerfile

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Check new release
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git fetch --tags
          export TAG=$(git tag | tail -n 1)
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: success() && env.TAG != ''

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: success() && env.TAG != ''

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: success() && env.TAG != ''
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: success() && env.TAG != ''
        with:
          context: .
          push: true
          tags: |
            zhangsean/speedtest-web:latest,
            zhangsean/speedtest-web:${{ env.TAG }}
